import { GrovsClient } from './core/client';
import type { GrovsConfig } from './core/config';
import { LinkGenerator } from './links/links';
import { MessagesService, type GrovsMessage } from './messages/messages';
import { MessagesUI } from './messages/messages-ui';
import { getDocument } from './core/environment';
import { Logger, type LogLevel } from './logging/logger';
import type { CreateLinkParams } from './net/api';
import { GrovsV1 } from './compat/v1';
import type { ScreenNameProvider } from './tracking/auto-screen-tracker';
import type { CustomPurchase } from './events/payment-events-handler';

let client: GrovsClient | null = null;
let links: LinkGenerator | null = null;
let messages: MessagesService | null = null;
let ui: MessagesUI | null = null;

const fallbackLogger = new Logger();

function notConfigured(method: string): void {
  fallbackLogger.warn(`${method}() called before configure(); the call is a no-op.`);
}

function messagesUI(): MessagesUI | null {
  const doc = getDocument();
  if (!doc || !messages || !client) return null;
  ui ??= new MessagesUI(doc, messages, client.log);
  return ui;
}

/**
 * The v2 facade. Mirrors the static shape of the iOS Grovs class so the two
 * SDKs read as one product.
 */
export const Grovs = {
  async configure(config: GrovsConfig): Promise<boolean> {
    // React strict mode and hot reload call this twice. The per-client guard
    // cannot help here: a second call builds a *new* client, so without this
    // the previous one's flush interval, lifecycle listeners and History
    // patch stay live and everything is tracked twice.
    client?.dispose();

    client = new GrovsClient(config);
    links = new LinkGenerator(client);
    messages = new MessagesService(client);
    ui = null;
    // Automatic display needs the DOM surface, which lives here.
    client.messagesUI = messagesUI;
    return client.configure();
  },

  generateLink(params: CreateLinkParams): Promise<string | null> {
    if (!links) {
      notConfigured('generateLink');
      return Promise.resolve(null);
    }
    return links.generateLink(params);
  },

  get userIdentifier(): string | null {
    return client?.userIdentifier ?? null;
  },

  get userAttributes(): Record<string, unknown> | null {
    return client?.userAttributes ?? null;
  },

  setUserIdentifier(identifier: string | null): void {
    if (!client) return notConfigured('setUserIdentifier');
    client.setUserIdentifier(identifier);
  },

  setUserAttributes(attributes: Record<string, unknown> | null): void {
    if (!client) return notConfigured('setUserAttributes');
    client.setUserAttributes(attributes);
  },

  isAuthenticated(): boolean {
    return client?.isAuthenticated() ?? false;
  },

  setEnabled(enabled: boolean): void {
    if (!client) return notConfigured('setEnabled');
    client.setEnabled(enabled);
  },

  setDebugLevel(level: LogLevel): void {
    if (!client) {
      fallbackLogger.setLevel(level);
      return;
    }
    client.setDebugLevel(level);
  },

  // MARK: Analytics

  track(name: string, properties?: Record<string, unknown>, tags?: string[]): void {
    if (!client) return notConfigured('track');
    client.track(name, properties, tags);
  },

  trackScreenView(screenName: string, properties?: Record<string, unknown>): void {
    if (!client) return notConfigured('trackScreenView');
    client.trackScreenView(screenName, properties);
  },

  setGlobalTags(tags: string[] | null): void {
    if (!client) return notConfigured('setGlobalTags');
    client.setGlobalTags(tags);
  },

  setScreenAliases(aliases: Record<string, string>): void {
    if (!client) return notConfigured('setScreenAliases');
    client.setScreenAliases(aliases);
  },

  set screenNameProvider(provider: ScreenNameProvider | null) {
    if (!client) {
      notConfigured('screenNameProvider');
      return;
    }
    client.screenNameProvider = provider;
  },

  get screenNameProvider(): ScreenNameProvider | null {
    return client?.screenNameProvider ?? null;
  },

  /**
   * Fetches details for a link generated by the SDK in this environment.
   * Resolves null when the path is unknown.
   */
  linkDetails(path: string): Promise<Record<string, unknown> | null> {
    if (!links) {
      notConfigured('linkDetails');
      return Promise.resolve(null);
    }
    return links.linkDetails(path);
  },

  /**
   * Logs a purchase. Requires a Grovs Enterprise backend (GROVS_EE=true);
   * on a standard deployment this reports eventDispatchFailed naming the
   * requirement rather than retrying.
   */
  logCustomPurchase(purchase: CustomPurchase): Promise<boolean> {
    if (!client) {
      notConfigured('logCustomPurchase');
      return Promise.resolve(false);
    }
    return client.logCustomPurchase(purchase);
  },

  /**
   * Opens every message the console flagged for automatic display. Runs
   * automatically after configure(); this is for triggering a re-check.
   */
  displayAutomaticMessages(): Promise<void> {
    const surface = messagesUI();
    if (!surface) {
      notConfigured('displayAutomaticMessages');
      return Promise.resolve();
    }
    return surface.displayAutomaticMessages();
  },

  /**
   * Grants consent when configure() was called with requireConsent: true.
   * Migrates anything tracked meanwhile into durable storage and authenticates.
   */
  grantConsent(): Promise<boolean> {
    if (!client) {
      notConfigured('grantConsent');
      return Promise.resolve(false);
    }
    return client.grantConsent();
  },

  /** Clears stored identifiers, the session and the queued events. */
  reset(): void {
    if (!client) return notConfigured('reset');
    client.reset();
  },

  /** Drains the queue now, for integrators facing a hard navigation. */
  flush(): Promise<void> {
    if (!client) {
      notConfigured('flush');
      return Promise.resolve();
    }
    return client.flush();
  },

  allReceivedPayloadsSinceStartup(): Record<string, unknown>[] {
    return client?.allReceivedPayloadsSinceStartup() ?? [];
  },

  lastReceivedPayload(): Record<string, unknown> | null {
    return client?.lastReceivedPayload() ?? null;
  },

  showMessagesList(): Promise<void> {
    const surface = messagesUI();
    if (!surface) {
      notConfigured('showMessagesList');
      return Promise.resolve();
    }
    return surface.showMessagesList();
  },

  getMessages(page: number): Promise<GrovsMessage[]> {
    if (!messages) {
      notConfigured('getMessages');
      return Promise.resolve([]);
    }
    return messages.getMessages(page);
  },

  numberOfUnreadMessages(): Promise<number> {
    if (!messages) {
      notConfigured('numberOfUnreadMessages');
      return Promise.resolve(0);
    }
    return messages.numberOfUnreadMessages();
  },

  markMessageAsRead(id: number): Promise<boolean> {
    if (!messages) {
      notConfigured('markMessageAsRead');
      return Promise.resolve(false);
    }
    return messages.markMessageAsRead(id);
  },

  /** The deprecated v1 class. `new Grovs.V1(key, testEnv, callback)`. */
  V1: GrovsV1,
};

import { GrovsError } from './net/errors';
import { SDK_VERSION } from './version';

export { GrovsError };
export { SDK_VERSION };
export type { GrovsConfig, DeeplinkCallback } from './core/config';
export type { LogLevel, ErrorCallback } from './logging/logger';
export type { GrovsMessage } from './messages/messages';
export type { CreateLinkParams } from './net/api';
export type { ScreenNameProvider, ScreenNameDecision } from './tracking/auto-screen-tracker';
export type { CustomRedirects } from './net/api';
export type { CustomPurchase, TransactionType } from './events/payment-events-handler';
export { GrovsV1 };

export default Grovs;
